/* ============================================================
   DILINO STUDIO — FONTE ÚNICA DE PRODUTOS
   Edite um produto AQUI e ele muda na home e no catálogo.
   Para o botão "Comprar agora", cole o link da Yampi em link_checkout.
   Campos: codigo, nome, ambiente, descricao, descricaoLonga, medidas,
   material, acabamento, preco, preco_riscado, imagens{ambiente,detalhe,
   perfil,medidas}, link_checkout.
   ============================================================ */
window.DILINO_PRODUTOS = [
  { codigo:"DS-001", nome:"Suporte Vulcano", ambiente:"Cozinha", preco:440.7, preco_riscado:null,
    medidas:"60 × 40 × 40 cm", descricao:"Suporte industrial suspenso para forno e micro-ondas",
    descricaoLonga:"O Suporte Vulcano resolve na vertical o que o chão não precisa ocupar: suporte industrial suspenso para forno e micro-ondas. As junções são soldadas uma a uma e lixadas, o que apaga a marca da solda. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Ocupa 60 × 40 × 40 cm e foi dimensionado para o vaivém da cozinha.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-001.png", detalhe:"assets/DS-001-detalhe.png", perfil:null, medidas:"assets/DS-001-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1FZ9VTN8XI", yampiToken:"1FZ9VTN8XI" },
  { codigo:"DS-002", nome:"Estante Argos", ambiente:"Cozinha", preco:1675.7, preco_riscado:null,
    medidas:"101 × 160,7 × 36 cm", descricao:"Estante industrial de cozinha com bancada",
    descricaoLonga:"A Estante Argos deixa tudo à vista, com a estrutura aparente: estante industrial de cozinha com bancada. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Com 101 × 160,7 × 36 cm, entra na rotina da cozinha sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-002.png", detalhe:"assets/DS-002-detalhe.png", perfil:null, medidas:"assets/DS-002-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/DXMN7169WR", yampiToken:"DXMN7169WR" },
  { codigo:"DS-003", nome:"Prateleira Ravena", ambiente:"Cozinha", preco:599, preco_riscado:null,
    medidas:"90+90 × 70 × 25 cm", descricao:"Prateleira industrial de canto",
    descricaoLonga:"A Prateleira Ravena sai da parede e devolve o chão: prateleira industrial de canto. As junções são soldadas uma a uma e lixadas, o que apaga a marca da solda. O ferro galvanizado leva pintura fosca, que não reflete a luz nem marca digital; a madeira maciça fica no acabamento natural, com o veio à mostra. Mede 90+90 × 70 × 25 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-003.png", detalhe:"assets/DS-003-detalhe.png", perfil:null, medidas:"assets/DS-003-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/HURVT69YGW", yampiToken:"HURVT69YGW" },
  { codigo:"DS-004", nome:"Nicho Solano", ambiente:"Cozinha", preco:778.7, preco_riscado:null,
    medidas:"120 × 75 × 40 cm", descricao:"Nicho industrial suspenso duplo",
    descricaoLonga:"O Nicho Solano sai da parede e devolve o chão: nicho industrial suspenso duplo. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. São 120 cm de largura, 75 de altura e 40 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-004.png", detalhe:"assets/DS-004-detalhe.png", perfil:null, medidas:"assets/DS-004-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/5XAD8S0JOS", yampiToken:"5XAD8S0JOS" },
  { codigo:"DS-005", nome:"Nicho Ferrara", ambiente:"Cozinha", preco:628.25, preco_riscado:null,
    medidas:"58 × 86 × 30 cm", descricao:"Nicho industrial suspenso porta-utensílios",
    descricaoLonga:"O Nicho Ferrara sai da parede e devolve o chão: nicho industrial suspenso porta-utensílios. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. São 58 cm de largura, 86 de altura e 30 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-005.png", detalhe:"assets/DS-005-detalhe.png", perfil:null, medidas:"assets/DS-005-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3ZENOC8230", yampiToken:"3ZENOC8230" },
  { codigo:"DS-006", nome:"Kit Cairo", ambiente:"Cozinha", preco:499, preco_riscado:null,
    medidas:"70 × 30 × 25 cm", descricao:"Kit com 2 nichos industriais suspensos",
    descricaoLonga:"O Kit Cairo resolve na vertical o que o chão não precisa ocupar: kit com 2 nichos industriais suspensos. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Mede 70 × 30 × 25 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-006.png", detalhe:"assets/DS-006-detalhe.png", perfil:null, medidas:"assets/DS-006-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/81OOF6UJUV", yampiToken:"81OOF6UJUV" },
  { codigo:"DS-007", nome:"Suporte Enzo", ambiente:"Cozinha", preco:470.75, preco_riscado:null,
    medidas:"60 × 44 × 33 cm", descricao:"Suporte industrial suspenso para micro-ondas",
    descricaoLonga:"O Suporte Enzo sai da parede e devolve o chão: suporte industrial suspenso para micro-ondas. As junções são soldadas uma a uma e lixadas, o que apaga a marca da solda. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Com 60 × 44 × 33 cm, entra na rotina da cozinha sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-007.png", detalhe:"assets/DS-007-detalhe.png", perfil:null, medidas:"assets/DS-007-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/T6E2RIJIAZ", yampiToken:"T6E2RIJIAZ" },
  { codigo:"DS-008", nome:"Aparador Vitrali", ambiente:"Cozinha", preco:417.15, preco_riscado:null,
    medidas:"89 × 60 × 19 cm", descricao:"Aparador industrial de cozinha",
    descricaoLonga:"O Aparador Vitrali foi desenhado para aguentar peso e uso diário: aparador industrial de cozinha. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Com 89 × 60 × 19 cm, entra no vaivém da cozinha sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-008.png", detalhe:"assets/DS-008-detalhe.png", perfil:null, medidas:"assets/DS-008-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9QCDW97DQN", yampiToken:"9QCDW97DQN" },
  { codigo:"DS-009", nome:"Prateleira Milano", ambiente:"Cozinha", preco:505.75, preco_riscado:null,
    medidas:"120 × 41 × 20 cm", descricao:"Prateleira industrial dupla suspensa",
    descricaoLonga:"A Prateleira Milano resolve na vertical o que o chão não precisa ocupar: prateleira industrial dupla suspensa. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Ocupa 120 × 41 × 20 cm e foi dimensionada para o uso diário da cozinha.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-009.png", detalhe:"assets/DS-009-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3ZTSXBUF01", yampiToken:"3ZTSXBUF01" },
  { codigo:"DS-010", nome:"Carrinho Nômade", ambiente:"Cozinha", preco:549.55, preco_riscado:null,
    medidas:"55 × 75 × 30 cm", descricao:"Carrinho industrial de cozinha com rodízios",
    descricaoLonga:"O Carrinho Nômade é superfície de trabalho antes de ser móvel de decoração: carrinho industrial de cozinha com rodízios. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. São 55 cm de largura, 75 de altura e 30 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-010.png", detalhe:"assets/DS-010-detalhe.png", perfil:null, medidas:"assets/DS-010-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/ILM5M1A7LL", yampiToken:"ILM5M1A7LL" },
  { codigo:"DS-011", nome:"Prateleira Jasmin", ambiente:"Cozinha", preco:208.6, preco_riscado:null,
    medidas:"41 × 32 × 10 cm", descricao:"Prateleira industrial porta-canecas",
    descricaoLonga:"A Prateleira Jasmin sai da parede e devolve o chão: prateleira industrial porta-canecas. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. São 41 cm de largura, 32 de altura e 10 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-011.png", detalhe:null, perfil:"assets/DS-011-perfil.png", medidas:"assets/DS-011-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/2XRASXSJ8C", yampiToken:"2XRASXSJ8C" },
  { codigo:"DS-012", nome:"Escrivaninha Turim", ambiente:"Escritório", preco:768.9, preco_riscado:null,
    medidas:"118 × 75 × 53 cm", descricao:"Escrivaninha industrial com gaveta",
    descricaoLonga:"A Escrivaninha Turim foi desenhada para aguentar peso e uso diário: escrivaninha industrial com gaveta. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Mede 118 × 75 × 53 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-012.png", detalhe:null, perfil:"assets/DS-012-perfil.png", medidas:"assets/DS-012-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/E2V2HVP5W7", yampiToken:"E2V2HVP5W7" },
  { codigo:"DS-013", nome:"Mesa Órion", ambiente:"Escritório", preco:1930.6, preco_riscado:null,
    medidas:"180 × 118 × 70 cm", descricao:"Mesa gamer industrial com suporte para monitor",
    descricaoLonga:"A Mesa Órion foi desenhada para aguentar peso e uso diário: mesa gamer industrial com suporte para monitor. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Mede 180 × 118 × 70 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-013.png", detalhe:null, perfil:"assets/DS-013-perfil.png", medidas:"assets/DS-013-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/S3VLVNBEUY", yampiToken:"S3VLVNBEUY" },
  { codigo:"DS-014", nome:"Escrivaninha Toscana", ambiente:"Escritório", preco:515.9, preco_riscado:null,
    medidas:"67 × 78 × 30 cm", descricao:"Escrivaninha industrial com nichos laterais",
    descricaoLonga:"A Escrivaninha Toscana foi desenhada para aguentar peso e uso diário: escrivaninha industrial com nichos laterais. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Ocupa 67 × 78 × 30 cm e foi dimensionada para o expediente em casa.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-014.png", detalhe:null, perfil:"assets/DS-014-perfil.png", medidas:"assets/DS-014-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/K4A2NI5S3H", yampiToken:"K4A2NI5S3H" },
  { codigo:"DS-015", nome:"Mesa Atlas", ambiente:"Escritório", preco:2038.3, preco_riscado:null,
    medidas:"200 × 74 × 90 cm", descricao:"Mesa de reunião industrial corporativa",
    descricaoLonga:"A Mesa Atlas foi desenhada para aguentar peso e uso diário: mesa de reunião industrial corporativa. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Com 200 × 74 × 90 cm, entra na mesa de trabalho sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-015.png", detalhe:null, perfil:"assets/DS-015-perfil.png", medidas:"assets/DS-015-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FRP8JQSX8M", yampiToken:"FRP8JQSX8M" },
  { codigo:"DS-016", nome:"Nicho Módena", ambiente:"Escritório", preco:471.38, preco_riscado:null,
    medidas:"70 × 70 × 20 cm", descricao:"Nicho de parede modular com compartimentos assimétricos · Ferro galvanizado · Madeira maciça",
    descricaoLonga:"O Nicho Módena resolve na vertical o que o chão não precisa ocupar: nicho de parede modular com compartimentos assimétricos. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Ocupa 70 × 70 × 20 cm e foi dimensionado para o expediente em casa.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-016.png", detalhe:null, perfil:null, medidas:"assets/DS-016-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/12NCHBX0CR", yampiToken:"12NCHBX0CR" },
  { codigo:"DS-017", nome:"Prateleira Paralela", ambiente:"Escritório", preco:471.38, preco_riscado:null,
    medidas:"120 × 88 × 20 cm", descricao:"Prateleira industrial dupla para livros",
    descricaoLonga:"A Prateleira Paralela tem duas tábuas de madeira maciça presas a laterais de ferro soldadas à mão. Segura livro pesado sem envergar e deixa a parede do escritório organizada. Pintura fosca, junções lixadas. Mede 120 × 88 × 20 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-017.png", detalhe:"assets/DS-017-detalhe.png", perfil:null, medidas:"assets/DS-017-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1XD4G89DMF", yampiToken:"1XD4G89DMF" },
  { codigo:"DS-018", nome:"Escrivaninha Nórdica", ambiente:"Escritório", preco:279, preco_riscado:null,
    medidas:"80 × 77 × 45 cm", descricao:"Escrivaninha industrial compacta slim",
    descricaoLonga:"A Escrivaninha Nórdica foi desenhada para aguentar peso e uso diário: escrivaninha industrial compacta slim. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O ferro galvanizado leva pintura fosca, que não reflete a luz nem marca digital; a madeira maciça fica no acabamento natural, com o veio à mostra. São 80 cm de largura, 77 de altura e 45 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-018.png", detalhe:"assets/DS-018-detalhe.png", perfil:null, medidas:"assets/DS-018-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/K2I53016FS", yampiToken:"K2I53016FS" },
  { codigo:"DS-019", nome:"Home Office Loft", ambiente:"Escritório", preco:814.8, preco_riscado:null,
    medidas:"100 × 80 × 55 cm", descricao:"Estação de trabalho suspensa com prateleiras",
    descricaoLonga:"O Home Office Loft é superfície de trabalho antes de ser móvel de decoração: estação de trabalho suspensa com prateleiras. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. O ferro galvanizado leva pintura fosca, que não reflete a luz nem marca digital; a madeira maciça fica no acabamento natural, com o veio à mostra. Mede 100 × 80 × 55 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-019.png", detalhe:"assets/DS-019-detalhe.png", perfil:null, medidas:"assets/DS-019-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3QIZN2V8HB", yampiToken:"3QIZN2V8HB" },
  { codigo:"DS-020", nome:"Suporte Kraft", ambiente:"Escritório", preco:259, preco_riscado:null,
    medidas:"50 × 22 × 40 cm", descricao:"Suporte industrial suspenso para impressora",
    descricaoLonga:"O Suporte Kraft sai da parede e devolve o chão: suporte industrial suspenso para impressora. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Mede 50 × 22 × 40 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-020.png", detalhe:"assets/DS-020-detalhe.png", perfil:null, medidas:"assets/DS-020-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/84V7JF8IN7", yampiToken:"84V7JF8IN7" },
  { codigo:"DS-021", nome:"Mesa Cortez", ambiente:"Escritório", preco:199, preco_riscado:null,
    medidas:"60 × 50 × 30 cm", descricao:"Mesa lateral industrial em C para sofá",
    descricaoLonga:"A Mesa Cortez é superfície de trabalho antes de ser móvel de decoração: mesa lateral industrial em C para sofá. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O ferro galvanizado leva pintura fosca, que não reflete a luz nem marca digital; a madeira maciça fica no acabamento natural, com o veio à mostra. Ocupa 60 × 50 × 30 cm e foi dimensionada para a mesa de trabalho.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-021.png", detalhe:"assets/DS-021-detalhe.png", perfil:null, medidas:"assets/DS-021-medidas.jpg" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/IR5Q58A0CR", yampiToken:"IR5Q58A0CR" },
  { codigo:"DS-022", nome:"Closet Verona", ambiente:"Quarto", preco:1599, preco_riscado:null,
    medidas:"120 × 180 × 40 cm", descricao:"Closet industrial aberto com iluminação LED",
    descricaoLonga:"O Closet Verona organiza sem fechar o ambiente: closet industrial aberto com iluminação LED. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Com 120 × 180 × 40 cm, entra na rotina do quarto sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-022.png", detalhe:"assets/DS-022-detalhe.png", perfil:null, medidas:"assets/DS-022-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/NN9QOEMAF1", yampiToken:"NN9QOEMAF1" },
  { codigo:"DS-023", nome:"Criado-Mudo Onyx", ambiente:"Quarto", preco:599, preco_riscado:null,
    medidas:"50 × 45 × 40 cm", descricao:"Criado-mudo industrial com gaveta basculante",
    descricaoLonga:"O Criado-Mudo Onyx deixa tudo à vista, com a estrutura aparente: criado-mudo industrial com gaveta basculante. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Mede 50 × 45 × 40 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-023.png", detalhe:"assets/DS-023-detalhe.png", perfil:null, medidas:"assets/DS-023-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/OXW6SN8AMI", yampiToken:"OXW6SN8AMI" },
  { codigo:"DS-024", nome:"Banco Aurora", ambiente:"Quarto", preco:399, preco_riscado:null,
    medidas:"60 × 45 × 30 cm", descricao:"Banco sapateira industrial",
    descricaoLonga:"O Banco Aurora é superfície de trabalho antes de ser móvel de decoração: banco sapateira industrial. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Com 60 × 45 × 30 cm, entra na rotina do quarto sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-024.png", detalhe:"assets/DS-024-detalhe.png", perfil:null, medidas:"assets/DS-024-medidas.jpg" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9N5OJCNLTT", yampiToken:"9N5OJCNLTT" },
  { codigo:"DS-025", nome:"Sapateira Carbon", ambiente:"Quarto", preco:519, preco_riscado:null,
    medidas:"75 × 90 × 35 cm", descricao:"Sapateira industrial compacta 2 níveis",
    descricaoLonga:"A Sapateira Carbon organiza sem fechar o ambiente: sapateira industrial compacta 2 níveis. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Mede 75 × 90 × 35 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-025.png", detalhe:"assets/DS-025-detalhe.png", perfil:null, medidas:"assets/DS-025-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KCJO4LLLKM", yampiToken:"KCJO4LLLKM" },
  { codigo:"DS-026", nome:"Prateleira Sienna", ambiente:"Quarto", preco:599, preco_riscado:null,
    medidas:"100 × 37 × 20 cm", descricao:"Prateleira industrial dupla de cabeceira",
    descricaoLonga:"A Prateleira Sienna sai da parede e devolve o chão: prateleira industrial dupla de cabeceira. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Mede 100 × 37 × 20 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-026.png", detalhe:"assets/DS-026-detalhe.png", perfil:null, medidas:"assets/DS-026-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/Q1E8BGLDDS", yampiToken:"Q1E8BGLDDS" },
  { codigo:"DS-027", nome:"Criado-Mudo Cedro", ambiente:"Quarto", preco:659.9, preco_riscado:null,
    medidas:"60 × 60 × 40 cm", descricao:"Criado-mudo industrial com nicho aberto",
    descricaoLonga:"O Criado-Mudo Cedro organiza sem fechar o ambiente: criado-mudo industrial com nicho aberto. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Com 60 × 60 × 40 cm, entra na rotina do quarto sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-027.png", detalhe:"assets/DS-027-detalhe.png", perfil:null, medidas:"assets/DS-027-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/LO8EJ8KKCV", yampiToken:"LO8EJ8KKCV" },
  { codigo:"DS-028", nome:"Sapateira Nero", ambiente:"Quarto", preco:519, preco_riscado:null,
    medidas:"75 × 90 × 35 cm", descricao:"Sapateira industrial escalonada",
    descricaoLonga:"A Sapateira Nero deixa tudo à vista, com a estrutura aparente: sapateira industrial escalonada. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Ocupa 75 × 90 × 35 cm e foi dimensionada para o descanso do quarto.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-028.png", detalhe:"assets/DS-028-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/ASEMZR3EAP", yampiToken:"ASEMZR3EAP" },
  { codigo:"DS-029", nome:"Criado-Mudo Lumière", ambiente:"Quarto", preco:779.5, preco_riscado:null,
    medidas:"50 × 40 × 40 cm", descricao:"Criado-mudo industrial com gaveta e tampo de vidro",
    descricaoLonga:"O Criado-Mudo Lumière deixa tudo à vista, com a estrutura aparente: criado-mudo industrial com gaveta e tampo de vidro. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Mede 50 × 40 × 40 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-029.png", detalhe:"assets/DS-029-detalhe.png", perfil:null, medidas:"assets/DS-029-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/7Z9H9GCLOP", yampiToken:"7Z9H9GCLOP" },
  { codigo:"DS-030", nome:"Arara Amêndoa", ambiente:"Quarto", preco:1680, preco_riscado:null,
    medidas:"100 × 180 × 34 cm", descricao:"Arara closet industrial com prateleiras",
    descricaoLonga:"A Arara Amêndoa deixa tudo à vista, com a estrutura aparente: arara closet industrial com prateleiras. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Com 100 × 180 × 34 cm, entra no descanso do quarto sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-030.png", detalhe:"assets/DS-030-detalhe.png", perfil:null, medidas:"assets/DS-030-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QIZWQUPHRG", yampiToken:"QIZWQUPHRG" },
  { codigo:"DS-031", nome:"Cabideiro Bruma", ambiente:"Quarto", preco:255, preco_riscado:null,
    medidas:"40 × 30 × 26 cm", descricao:"Cabideiro de parede com prateleira · Ferro galvanizado · Madeira maciça",
    descricaoLonga:"O Cabideiro Bruma sai da parede e devolve o chão: cabideiro de parede com prateleira. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Mede 40 × 30 × 26 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-031.png", detalhe:"assets/DS-031-detalhe.png", perfil:null, medidas:"assets/DS-031-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1MSXAFNU4W", yampiToken:"1MSXAFNU4W" },
  { codigo:"DS-032", nome:"Mesa Havana", ambiente:"Quarto", preco:419, preco_riscado:null,
    medidas:"47 × 45 × 45 cm", descricao:"Mesa lateral industrial de cabeceira",
    descricaoLonga:"A Mesa Havana foi desenhada para aguentar peso e uso diário: mesa lateral industrial de cabeceira. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Mede 47 × 45 × 45 cm. Confira o vão e a passagem antes de comprar.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-032.png", detalhe:"assets/DS-032-detalhe.png", perfil:null, medidas:"assets/DS-032-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/AOT16EUG6F", yampiToken:"AOT16EUG6F" },
  { codigo:"DS-033", nome:"Prateleira Halo", ambiente:"Quarto", preco:479, preco_riscado:null,
    medidas:"200 × 80 × 25 cm", descricao:"Prateleira de parede tripla com iluminação LED",
    descricaoLonga:"A Prateleira Halo tem três planos de madeira maciça em estrutura de ferro, com iluminação LED que valoriza o que fica exposto. São 2 metros de largura: ocupa a parede do quarto e ilumina sem precisar de luminária. Solda feita à mão e lixada, pintura fosca.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-033.png", detalhe:"assets/DS-033-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KGE0B6OAX6", yampiToken:"KGE0B6OAX6" },
  { codigo:"DS-034", nome:"Criado-Mudo Terrano", ambiente:"Quarto", preco:299, preco_riscado:null,
    medidas:"40 × 60 × 30 cm", descricao:"Criado-mudo industrial com tampo e prateleira",
    descricaoLonga:"O Criado-Mudo Terrano tem tampo e prateleira de madeira maciça sobre estrutura de ferro soldada à mão. Espaço para o abajur em cima e para os livros embaixo. Mede 40 × 60 × 30 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-034.png", detalhe:"assets/DS-034-detalhe.png", perfil:null, medidas:"assets/DS-034-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/RTNBETIK05", yampiToken:"RTNBETIK05" },
  { codigo:"DS-035", nome:"Cabideiro Linho", ambiente:"Quarto", preco:370, preco_riscado:null,
    medidas:"50 × 120 × 32 cm", descricao:"Cabideiro industrial suspenso com prateleira",
    descricaoLonga:"O Cabideiro Linho sai da parede e devolve o chão: cabideiro industrial suspenso com prateleira. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Com 50 × 120 × 32 cm, entra na rotina do quarto sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-035.png", detalhe:null, perfil:"assets/DS-035-perfil.png", medidas:"assets/DS-035-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FZJJD127VH", yampiToken:"FZJJD127VH" },
  { codigo:"DS-036", nome:"Nicho Ostra", ambiente:"Banheiro", preco:499, preco_riscado:null,
    medidas:"60 × 50 × 15 cm", descricao:"Nicho industrial suspenso de banheiro 2 níveis",
    descricaoLonga:"O Nicho Ostra sai da parede e devolve o chão: nicho industrial suspenso de banheiro 2 níveis. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. Ocupa 60 × 50 × 15 cm e foi dimensionado para a rotina do banheiro.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-036.png", detalhe:"assets/DS-036-detalhe.png", perfil:null, medidas:"assets/DS-036-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FVSG2Z4SEW", yampiToken:"FVSG2Z4SEW" },
  { codigo:"DS-037", nome:"Prateleira Costa", ambiente:"Banheiro", preco:580, preco_riscado:null,
    medidas:"60 × 15 × 30 cm", descricao:"Prateleira industrial de banheiro com toalheiro",
    descricaoLonga:"A Prateleira Costa sai da parede e devolve o chão: prateleira industrial de banheiro com toalheiro. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Ocupa 60 × 15 × 30 cm e foi dimensionada para a rotina do banheiro.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-037.png", detalhe:"assets/DS-037-detalhe.png", perfil:null, medidas:"assets/DS-037-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/RZWBNE5J49", yampiToken:"RZWBNE5J49" },
  { codigo:"DS-038", nome:"Porta-Toalhas Salina", ambiente:"Banheiro", preco:275, preco_riscado:null,
    medidas:"30 × 60 × 15 cm", descricao:"Porta-toalhas vertical de parede com 2 prateleiras",
    descricaoLonga:"O Porta-Toalhas Salina guarda toalhas enroladas na vertical e ocupa só 15 cm de profundidade na parede do banheiro. Estrutura de ferro soldada à mão, prateleiras de madeira maciça e pintura fosca. Mede 30 × 60 × 15 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-038.png", detalhe:"assets/DS-038-detalhe.png", perfil:null, medidas:"assets/DS-038-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9XAP2LOVCG", yampiToken:"9XAP2LOVCG" },
  { codigo:"DS-039", nome:"Estante Maresia", ambiente:"Banheiro", preco:699, preco_riscado:null,
    medidas:"60 × 80 × 20 cm", descricao:"Estante industrial de banheiro 4 prateleiras",
    descricaoLonga:"A Estante Maresia deixa tudo à vista, com a estrutura aparente: estante industrial de banheiro 4 prateleiras. As junções são soldadas uma a uma e lixadas, o que apaga a marca da solda. A pintura fosca no ferro galvanizado não devolve o reflexo da luz, e a madeira maciça entra crua, apenas selada. São 60 cm de largura, 80 de altura e 20 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-039.png", detalhe:"assets/DS-039-detalhe.png", perfil:null, medidas:"assets/DS-039-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/SA87DUH2PF", yampiToken:"SA87DUH2PF" },
  { codigo:"DS-040", nome:"Torre Abissal", ambiente:"Banheiro", preco:309, preco_riscado:null,
    medidas:"30 × 120 × 15 cm", descricao:"Torre industrial vertical suspensa de banheiro",
    descricaoLonga:"A Torre Abissal organiza sem fechar o ambiente: torre industrial vertical suspensa de banheiro. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Ocupa 30 × 120 × 15 cm e foi dimensionada para a umidade do banheiro.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-040.png", detalhe:"assets/DS-040-detalhe.png", perfil:null, medidas:"assets/DS-040-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/GJ2MBH3GEG", yampiToken:"GJ2MBH3GEG" },
  { codigo:"DS-041", nome:"Toalheiro Escada", ambiente:"Banheiro", preco:357, preco_riscado:null,
    medidas:"60 × 30 × 15 cm", descricao:"Toalheiro industrial suspenso com prateleira",
    descricaoLonga:"O Toalheiro Escada sai da parede e devolve o chão: toalheiro industrial suspenso com prateleira. Cada junção é soldada à mão e depois lixada, então não sobra emenda aparente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Com 60 × 30 × 15 cm, entra no vapor do banheiro sem pedir obra.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-041.png", detalhe:null, perfil:"assets/DS-041-perfil.png", medidas:"assets/DS-041-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QV5Y10946M", yampiToken:"QV5Y10946M" },
  { codigo:"DS-042", nome:"Toalheiro Mistral", ambiente:"Banheiro", preco:285, preco_riscado:null,
    medidas:"50 × 75 × 15 cm", descricao:"Toalheiro industrial de piso com 3 barras",
    descricaoLonga:"O Toalheiro Mistral fica de pé, sem furar parede: três barras de ferro em alturas diferentes para toalhas de banho e de rosto. Estrutura soldada à mão e pintura fosca. Mede 50 × 75 × 15 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-042.png", detalhe:"assets/DS-042-detalhe.png", perfil:null, medidas:"assets/DS-042-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/GGOS0HXUS2", yampiToken:"GGOS0HXUS2" },
  { codigo:"DS-043", nome:"Prateleira Duna", ambiente:"Banheiro", preco:260, preco_riscado:null,
    medidas:"50 × 70 × 15 cm", descricao:"Prateleira de parede com 2 níveis e barra toalheiro",
    descricaoLonga:"A Prateleira Duna junta duas prateleiras de madeira maciça e uma barra para toalha na mesma peça de parede. Organiza o banheiro com só 15 cm de profundidade. Ferro soldado à mão, pintura fosca. Mede 50 × 70 × 15 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-043.png", detalhe:null, perfil:"assets/DS-043-perfil.png", medidas:"assets/DS-043-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QWY07YGDY4", yampiToken:"QWY07YGDY4" },
  { codigo:"DS-044", nome:"Bancada Coral", ambiente:"Banheiro", preco:699, preco_riscado:null,
    medidas:"59,5 × 46,8 × 37 cm", descricao:"Bancada industrial suspensa de banheiro com toalheiro",
    descricaoLonga:"A Bancada Coral é superfície de trabalho antes de ser móvel de decoração: bancada industrial suspensa de banheiro com toalheiro. A estrutura é soldada à mão peça por peça, e cada junção é lixada rente. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. Ocupa 59,5 × 46,8 × 37 cm e foi dimensionada para a rotina do banheiro.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-044.png", detalhe:null, perfil:"assets/DS-044-perfil.png", medidas:"assets/DS-044-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/7XLPYLT9RB", yampiToken:"7XLPYLT9RB" },
  { codigo:"DS-045", nome:"Aparador Skyline", ambiente:"Sala de Estar", preco:489, preco_riscado:null,
    medidas:"80 × 75,5 × 30,5 cm", descricao:"Aparador console de 2 níveis",
    descricaoLonga:"O Aparador Skyline tem dois tampos de madeira maciça sobre estrutura de ferro. Estreito o bastante para atrás do sofá ou no hall, firme para abajur, livros e decoração. Solda feita à mão, pintura fosca. Mede 80 × 75,5 × 30,5 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-045.png", detalhe:null, perfil:"assets/DS-045-perfil.png", medidas:"assets/DS-045-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/SJE0S041S5", yampiToken:"SJE0S041S5" },
  { codigo:"DS-046", nome:"Floreira Esguia", ambiente:"Sala de Estar", preco:199, preco_riscado:null,
    medidas:"40 × 70 × 20 cm", descricao:"Suporte de plantas em Z com 3 níveis",
    descricaoLonga:"A Floreira Esguia tem desenho em Z com três apoios de madeira maciça para vasos, em alturas diferentes. Ocupa só 40 × 20 cm de chão e leva as plantas para perto da janela. Ferro soldado à mão, pintura fosca. Mede 40 × 70 × 20 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-046.png", detalhe:"assets/DS-046-detalhe.png", perfil:null, medidas:"assets/DS-046-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/D8TLJHMFP0", yampiToken:"D8TLJHMFP0" },
  { codigo:"DS-047", nome:"Estante Lateral Horizonte", ambiente:"Sala de Estar", preco:599, preco_riscado:null,
    medidas:"40 × 80 × 25,5 cm", descricao:"Estante baixa de 3 níveis para lateral de sofá",
    descricaoLonga:"A Estante Lateral Horizonte encosta no braço do sofá e faz as vezes de mesa lateral e de estante: três níveis para livros, xícara e decoração. Estrutura de ferro soldada à mão e pintura fosca. Mede 40 × 80 × 25,5 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-047.png", detalhe:"assets/DS-047-detalhe.png", perfil:null, medidas:"assets/DS-047-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/79Z4INI76M", yampiToken:"79Z4INI76M" },
  { codigo:"DS-048", nome:"Prateleira Degrau", ambiente:"Sala de Estar", preco:550, preco_riscado:null,
    medidas:"180 × 50 × 24 cm", descricao:"Prateleira de parede escalonada com 3 níveis",
    descricaoLonga:"A Prateleira Degrau tem três tábuas de madeira maciça desencontradas por montantes de ferro, em um desenho escalonado que ocupa a parede da sala inteira. Solda feita à mão, pintura fosca. Mede 180 × 50 × 24 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-048.png", detalhe:"assets/DS-048-detalhe.png", perfil:null, medidas:"assets/DS-048-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/EAAN8RC2EI", yampiToken:"EAAN8RC2EI" },
  { codigo:"DS-049", nome:"Rack Abraço", ambiente:"Sala de Estar", preco:909, preco_riscado:null,
    medidas:"170 × 70 × 40 cm", descricao:"Rack de TV industrial de 2 níveis",
    descricaoLonga:"O Rack Abraço tem dois níveis de madeira maciça sobre estrutura de ferro: TV em cima, aparelhos e cestos embaixo. São 1,70 m de largura para salas amplas. Solda feita à mão e lixada, pintura fosca. Mede 170 × 70 × 40 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-049.png", detalhe:"assets/DS-049-detalhe.png", perfil:null, medidas:"assets/DS-049-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QV5BM83FF3", yampiToken:"QV5BM83FF3" },
  { codigo:"DS-050", nome:"Mesa Litoral", ambiente:"Sala de Estar", preco:459, preco_riscado:null,
    medidas:"70 × 34 × 60 cm", descricao:"Mesa de centro com tampo claro e base em U",
    descricaoLonga:"A Mesa Litoral foi desenhada para aguentar peso e uso diário: mesa de centro com tampo claro e base em U. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. Ferro galvanizado com pintura fosca de um lado, madeira maciça no tom natural do outro — o contraste é o desenho da peça. São 70 cm de largura, 34 de altura e 60 de profundidade — vale medir o lugar antes.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-050.png", detalhe:"assets/DS-050-detalhe.png", perfil:null, medidas:"assets/DS-050-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KTQ43U58CD", yampiToken:"KTQ43U58CD" },
  { codigo:"DS-051", nome:"Painel Cinema", ambiente:"Sala de Estar", preco:1499, preco_riscado:null,
    medidas:"200 × 185 × 34 cm", descricao:"Painel rack de TV com estante lateral",
    descricaoLonga:"O Painel Cinema resolve na vertical o que o chão não precisa ocupar: painel rack de TV com estante lateral. A solda é feita à mão e lixada até desaparecer, sem emenda à vista. O acabamento é pintura fosca sobre ferro galvanizado, sem brilho, e a madeira maciça mantém o veio aparente. Ocupa 200 × 185 × 34 cm e foi dimensionado para a sala.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-051.png", detalhe:"assets/DS-051-detalhe.png", perfil:null, medidas:"assets/DS-051-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/28H4HJMHSV", yampiToken:"28H4HJMHSV" },
  { codigo:"DS-052", nome:"Prateleira Aura", ambiente:"Sala de Estar", preco:379, preco_riscado:null,
    medidas:"80 × 80 × 20 cm", descricao:"Prateleira de parede toda em ferro com 3 níveis",
    descricaoLonga:"A Prateleira Aura é toda em ferro: três planos pretos presos a duas laterais que ficam em pé na parede. Leve no visual, firme no uso — segura livro, vaso e peça de decoração sem envergar. A solda é feita à mão e lixada, e a pintura fosca não marca. São 80 cm de largura, 80 de altura e 20 de profundidade.",
    material:"Ferro galvanizado", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado",
    imagens:{ ambiente:"assets/DS-052.png", detalhe:"assets/DS-052-detalhe.png", perfil:null, medidas:"assets/DS-052-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QNAPA438A0", yampiToken:"QNAPA438A0" },
  { codigo:"DS-053", nome:"Cômoda Brutalista", ambiente:"Quarto", preco:1290, preco_riscado:null,
    medidas:"100 × 85 × 45 cm", descricao:"Cômoda de ferro com 3 gavetas efeito cimento",
    descricaoLonga:"A Cômoda Brutalista tem três gavetas largas com frente cinza efeito cimento, emolduradas por uma estrutura de ferro aparente. Cabe roupa, toalha e o que mais precisar sumir de vista. A estrutura vazada deixa a peça leve mesmo com 1 metro de largura. Mede 100 × 85 × 45 cm, com 15 cm de vão livre do chão.",
    material:"Ferro galvanizado · Gavetas efeito cimento", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado com gavetas efeito cimento",
    imagens:{ ambiente:"assets/DS-053.png", detalhe:"assets/DS-053-detalhe.png", perfil:null, medidas:"assets/DS-053-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/Q15FHKNDD5", yampiToken:"Q15FHKNDD5" },
  { codigo:"DS-054", nome:"Estante Hexa", ambiente:"Sala de Estar", preco:649, preco_riscado:null,
    medidas:"80 × 100 × 30 cm", descricao:"Estante de ferro e madeira com prateleiras em desenho hexagonal",
    descricaoLonga:"A Estante Hexa quebra a linha reta: duas prateleiras de madeira se encaixam num desenho hexagonal no meio da peça. Resultado: uma estante que já é decoração antes de receber qualquer objeto. Madeira maciça no tom natural, ferro preto fosco e solda lixada até sumir. Ocupa 80 × 100 × 30 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-054.png", detalhe:"assets/DS-054-detalhe.png", perfil:null, medidas:"assets/DS-054-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/YKRSVGUSMI", yampiToken:"YKRSVGUSMI" },
  { codigo:"DS-055", nome:"Banqueta Xis", ambiente:"Cozinha", preco:449, preco_riscado:null,
    medidas:"42 × 95 × 42 cm", descricao:"Banqueta alta com encosto em X e assento estofado",
    descricaoLonga:"A Banqueta Xis tem encosto com o X clássico e assento estofado em tecido grafite. Com o assento a 65 cm do chão, encaixa em bancada e ilha de cozinha. Apoio para os pés na altura certa e estrutura de ferro soldada à mão. São 95 cm de altura total sobre uma base de 42 × 42 cm.",
    material:"Ferro galvanizado · Assento estofado", acabamento:"Pintura fosca · Assento em tecido grafite", materialCurto:"ferro galvanizado e assento estofado",
    imagens:{ ambiente:"assets/DS-055.png", detalhe:"assets/DS-055-detalhe.png", perfil:null, medidas:"assets/DS-055-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/NPJSXO019E", yampiToken:"NPJSXO019E" },
  { codigo:"DS-056", nome:"Conjunto Bistrô", ambiente:"Cozinha", preco:1190, preco_riscado:null,
    medidas:"120 × 105 × 40 cm", descricao:"Mesa alta com 2 banquetas em ferro e madeira",
    descricaoLonga:"O Conjunto Bistrô vem com a mesa alta e duas banquetas, todas com tampo de madeira maciça e base de ferro. A mesa tem só 40 cm de profundidade: encosta na parede e transforma um canto parado em lugar de café ou happy hour. Mesa com 120 × 105 × 40 cm; banquetas com assento de 35 cm e 75 cm de altura.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-056.png", detalhe:"assets/DS-056-detalhe.png", perfil:null, medidas:"assets/DS-056-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/AVC9MFR70K", yampiToken:"AVC9MFR70K" },
  { codigo:"DS-057", nome:"Criado-Mudo Noir", ambiente:"Quarto", preco:649, preco_riscado:null,
    medidas:"45 × 60 × 40 cm", descricao:"Criado-mudo de ferro com 2 gavetas pretas",
    descricaoLonga:"O Criado-Mudo Noir é todo preto: duas gavetas encaixadas numa estrutura de ferro aparente, com tampo e vão livre embaixo. Guarda o que fica na cabeceira e ainda sobra espaço para a luminária. Visual limpo, pintura fosca, solda lixada. Mede 45 × 60 × 40 cm.",
    material:"Ferro galvanizado · Gavetas pretas", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado",
    imagens:{ ambiente:"assets/DS-057.png", detalhe:"assets/DS-057-detalhe.png", perfil:null, medidas:"assets/DS-057-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/17MGS7AIL1", yampiToken:"17MGS7AIL1" },
  { codigo:"DS-058", nome:"Escrivaninha Essencial", ambiente:"Escritório", preco:649, preco_riscado:null,
    medidas:"120 × 75 × 60 cm", descricao:"Escrivaninha com tampo de madeira e pés de ferro em U",
    descricaoLonga:"A Escrivaninha Essencial é o básico bem feito: tampo de madeira maciça de 120 × 60 cm sobre pés de ferro em U. Espaço para monitor, notebook e o que o dia pedir, sem travessa atrapalhando as pernas. Solda feita à mão e lixada, pintura fosca. Altura de 75 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-058.png", detalhe:"assets/DS-058-detalhe.png", perfil:null, medidas:"assets/DS-058-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FILUNRQG80", yampiToken:"FILUNRQG80" },
  { codigo:"DS-059", nome:"Banqueta Rústica", ambiente:"Cozinha", preco:289, preco_riscado:null,
    medidas:"42 × 65 × 42 cm", descricao:"Banqueta alta com assento de madeira e pés de ferro",
    descricaoLonga:"A Banqueta Rústica tem assento de madeira maciça e quatro pés de ferro com anel de apoio. Simples, resistente e na altura de bancada. Combina com cozinha, bar e área gourmet. São 65 cm de altura, assento de 35 cm e base de 42 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-059.png", detalhe:"assets/DS-059-detalhe.png", perfil:null, medidas:"assets/DS-059-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/41TW0A96WZ", yampiToken:"41TW0A96WZ" },
  { codigo:"DS-060", nome:"Cantoneira Zigue-Zague", ambiente:"Sala de Estar", preco:689, preco_riscado:null,
    medidas:"40 × 180 × 40 cm", descricao:"Estante de canto em ferro e madeira com 3 prateleiras",
    descricaoLonga:"A Cantoneira Zigue-Zague aproveita o canto que ninguém usa. São 180 cm de altura com três prateleiras de madeira maciça e uma estrutura de ferro que abre e fecha em zigue-zague. Peça de destaque para planta, livro e decoração. Cada lado mede 40 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-060.png", detalhe:"assets/DS-060-detalhe.png", perfil:null, medidas:"assets/DS-060-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/741IAF7LCA", yampiToken:"741IAF7LCA" },
  { codigo:"DS-061", nome:"Banqueta Lounge", ambiente:"Cozinha", preco:529, preco_riscado:null,
    medidas:"45 × 95 × 45 cm", descricao:"Banqueta alta com braços e assento estofado",
    descricaoLonga:"A Banqueta Lounge tem braços e encosto baixo em ferro e assento estofado em tecido grafite. Com o assento a 75 cm do chão, é feita para bancada alta e balcão de bar — conforto de poltrona na altura do balcão. São 95 cm de altura total e 45 cm de largura.",
    material:"Ferro galvanizado · Assento estofado", acabamento:"Pintura fosca · Assento em tecido grafite", materialCurto:"ferro galvanizado e assento estofado",
    imagens:{ ambiente:"assets/DS-061.png", detalhe:"assets/DS-061-detalhe.png", perfil:null, medidas:"assets/DS-061-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/C9DPI6YOXS", yampiToken:"C9DPI6YOXS" },
  { codigo:"DS-062", nome:"Sofá Varanda", ambiente:"Sala de Estar", preco:2790, preco_riscado:null,
    medidas:"200 × 75 × 80 cm", descricao:"Sofá com base de ferro e estofado cinza",
    descricaoLonga:"O Sofá Varanda tem base robusta de ferro e estofado cinza com três almofadas de encosto. Linhas retas, 2 metros de assento e uma presença que vai bem da sala à varanda gourmet. Mede 200 × 75 × 80 cm, com o assento a 42 cm do chão.",
    material:"Base em ferro galvanizado · Estofado em tecido", acabamento:"Pintura fosca · Estofado em tecido cinza", materialCurto:"base de ferro galvanizado e estofado em tecido",
    imagens:{ ambiente:"assets/DS-062.png", detalhe:"assets/DS-062-detalhe.png", perfil:null, medidas:"assets/DS-062-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/MRUZUH54WB", yampiToken:"MRUZUH54WB" },
  { codigo:"DS-063", nome:"Prateleira Ritmo", ambiente:"Sala de Estar", preco:399, preco_riscado:null,
    medidas:"86 × 58 × 25 cm", descricao:"Prateleira de parede com 3 tábuas desencontradas",
    descricaoLonga:"A Prateleira Ritmo tem três tábuas de madeira maciça desencontradas por montantes de ferro em alturas diferentes. O desenho assimétrico dá movimento à parede. Boa para livro, vaso e aquela peça que merece destaque. Ocupa 86 × 58 × 25 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-063.png", detalhe:"assets/DS-063-detalhe.png", perfil:null, medidas:"assets/DS-063-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3BAG4HJZ21", yampiToken:"3BAG4HJZ21" },
  { codigo:"DS-064", nome:"Adega Vertical", ambiente:"Cozinha", preco:349, preco_riscado:null,
    medidas:"36 × 150 × 12 cm", descricao:"Adega de parede em ferro para 9 garrafas",
    descricaoLonga:"A Adega Vertical guarda 9 garrafas deitadas na parede, uma sobre a outra, ocupando só 12 cm de profundidade. Um metro e meio de altura que vira ponto de destaque na cozinha, no bar ou na sala. Toda em ferro, com pintura fosca. Mede 36 × 150 × 12 cm.",
    material:"Ferro galvanizado", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado",
    imagens:{ ambiente:"assets/DS-064.png", detalhe:"assets/DS-064-detalhe.png", perfil:null, medidas:"assets/DS-064-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9E6E4YVPRE", yampiToken:"9E6E4YVPRE" },
  { codigo:"DS-065", nome:"Sofá Chaise Riviera", ambiente:"Sala de Estar", preco:3890, preco_riscado:null,
    medidas:"254 × 79 × 168 cm", descricao:"Sofá com chaise, base de ferro e estofado cinza",
    descricaoLonga:"O Sofá Chaise Riviera tem 2,54 m de assento e chaise de 1,68 m, sobre base de ferro aparente. Estofado cinza, linhas baixas e retas — pede sala ampla, varanda ou área de piscina. Altura de 79 cm e 86 cm de profundidade no assento.",
    material:"Base em ferro galvanizado · Estofado em tecido", acabamento:"Pintura fosca · Estofado em tecido cinza", materialCurto:"base de ferro galvanizado e estofado em tecido",
    imagens:{ ambiente:"assets/DS-065.png", detalhe:"assets/DS-065-detalhe.png", perfil:null, medidas:"assets/DS-065-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/BUZOPCTHJS", yampiToken:"BUZOPCTHJS" },
  { codigo:"DS-066", nome:"Mesa de Centro Duo", ambiente:"Sala de Estar", preco:1190, preco_riscado:null,
    medidas:"130 × 55 × 100 cm", descricao:"Mesa de centro com 2 tampos de vidro em alturas diferentes",
    descricaoLonga:"A Mesa de Centro Duo tem dois tampos de vidro em alturas diferentes, sobrepostos numa estrutura de ferro. O vidro deixa a sala respirar e a sobreposição dá movimento à peça. Vidro de 8 mm e ferro preto fosco. Ocupa 130 × 100 cm, com tampos a 55 e 40 cm de altura.",
    material:"Ferro galvanizado · Vidro 8 mm", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado e vidro",
    imagens:{ ambiente:"assets/DS-066.png", detalhe:"assets/DS-066-detalhe.png", perfil:null, medidas:"assets/DS-066-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/DSMXF61HTA", yampiToken:"DSMXF61HTA" },
  { codigo:"DS-067", nome:"Mesa de Centro Quadra", ambiente:"Sala de Estar", preco:459, preco_riscado:null,
    medidas:"90 × 32 × 35 cm", descricao:"Mesa de centro toda em ferro com laterais quadriculadas",
    descricaoLonga:"A Mesa de Centro Quadra é toda preta: tampo liso de ferro sobre uma estrutura com grade quadriculada nas laterais. Baixa e compacta, cabe em sala pequena. Pintura fosca e junções lixadas. Mede 90 × 32 × 35 cm.",
    material:"Ferro galvanizado", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado",
    imagens:{ ambiente:"assets/DS-067.png", detalhe:"assets/DS-067-detalhe.png", perfil:null, medidas:"assets/DS-067-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/99X7Q3IZL9", yampiToken:"99X7Q3IZL9" },
  { codigo:"DS-068", nome:"Escrivaninha Pauta", ambiente:"Escritório", preco:849, preco_riscado:null,
    medidas:"120 × 75 × 60 cm", descricao:"Escrivaninha com pés de ferro em barras verticais",
    descricaoLonga:"A Escrivaninha Pauta tem tampo de madeira maciça e pés de ferro com barras verticais, como linhas de pauta. Um detalhe que tira a mesa do comum sem roubar espaço: 120 × 60 cm livres para trabalhar, a 75 cm do chão.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-068.png", detalhe:"assets/DS-068-detalhe.png", perfil:null, medidas:"assets/DS-068-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/26XZPAUY0V", yampiToken:"26XZPAUY0V" },
  { codigo:"DS-069", nome:"Nichos Barista", ambiente:"Cozinha", preco:549, preco_riscado:null,
    medidas:"80 × 100 × 12 cm", descricao:"Kit com 5 nichos de parede para o cantinho do café",
    descricaoLonga:"Os Nichos Barista são cinco molduras de ferro com prateleiras de madeira maciça, para montar na parede do jeito que quiser. Pote de café, xícara, cafeteira — o cantinho do café fica organizado e à vista. O conjunto ocupa 80 × 100 cm, com prateleiras de 12 cm de profundidade.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-069.png", detalhe:"assets/DS-069-detalhe.png", perfil:null, medidas:"assets/DS-069-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9XC9L1BI8P", yampiToken:"9XC9L1BI8P" },
  { codigo:"DS-070", nome:"Estação Home Office U", ambiente:"Escritório", preco:1390, preco_riscado:null,
    medidas:"160 × 90 × 60 cm", descricao:"Mesa de home office com suporte para monitor e torres laterais",
    descricaoLonga:"A Estação Home Office U tem tampo elevado para o monitor, tampo de teclado rebaixado e duas torres laterais com prateleiras e base em tela para o gabinete. Tudo no lugar, sem cabo no chão. Madeira maciça e ferro preto. Mede 160 × 90 × 60 cm.",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-070.png", detalhe:"assets/DS-070-detalhe.png", perfil:null, medidas:"assets/DS-070-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/S8PMMZ5T3I", yampiToken:"S8PMMZ5T3I" },
  { codigo:"DS-071", nome:"Estante Vitrine", ambiente:"Sala de Estar", preco:1490, preco_riscado:null,
    medidas:"90 × 190 × 35 cm", descricao:"Estante de ferro com 5 prateleiras de vidro",
    descricaoLonga:"A Estante Vitrine empilha cinco módulos de ferro com prateleiras de vidro, cada um levemente deslocado do outro. São 1,90 m de altura que expõem livro, escultura e coleção como numa galeria. Vidro de 8 mm e ferro preto fosco. Mede 90 × 190 × 35 cm.",
    material:"Ferro galvanizado · Vidro 8 mm", acabamento:"Pintura fosca · Junções sem emenda", materialCurto:"ferro galvanizado e vidro",
    imagens:{ ambiente:"assets/DS-071.png", detalhe:null, perfil:null, medidas:"assets/DS-071-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KCGFR8HQTF", yampiToken:"KCGFR8HQTF" },
];
