/* ============================================================
   DILINO STUDIO — FONTE ÚNICA DE PRODUTOS
   Edite um produto AQUI e ele muda na home e no catálogo.
   Para o botão "Comprar agora", cole o link da Yampi em link_checkout.
   Campos: codigo, nome, ambiente, descricao, medidas, material,
   acabamento, preco, preco_riscado, imagens{ambiente,oficina,detalhe,
   perfil,medidas}, link_checkout.
   ============================================================ */
window.DILINO_PRODUTOS = [
  { codigo:"DS-001", nome:"Suporte Vulcano", ambiente:"Cozinha", preco:339, preco_riscado:null,
    medidas:"60 × 40 × 40 cm", descricao:"Suporte industrial suspenso para forno e micro-ondas",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-001.png", oficina:null, detalhe:"assets/DS-001-detalhe.png", perfil:null, medidas:"assets/DS-001-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1FZ9VTN8XI" },
  { codigo:"DS-002", nome:"Estante Argos", ambiente:"Cozinha", preco:1289, preco_riscado:null,
    medidas:"101 × 160,7 × 36 cm", descricao:"Estante industrial de cozinha com bancada",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-002.png", oficina:null, detalhe:"assets/DS-002-detalhe.png", perfil:null, medidas:"assets/DS-002-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/DXMN7169WR" },
  { codigo:"DS-003", nome:"Prateleira Ravena", ambiente:"Cozinha", preco:599, preco_riscado:null,
    medidas:"90+90 × 70 × 25 cm", descricao:"Prateleira industrial de canto",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-003.png", oficina:null, detalhe:"assets/DS-003-detalhe.png", perfil:null, medidas:"assets/DS-003-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/HURVT69YGW" },
  { codigo:"DS-004", nome:"Nicho Solano", ambiente:"Cozinha", preco:599, preco_riscado:null,
    medidas:"120 × 75 × 40 cm", descricao:"Nicho industrial suspenso duplo",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-004.png", oficina:null, detalhe:"assets/DS-004-detalhe.png", perfil:null, medidas:"assets/DS-004-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/5XAD8S0JOS" },
  { codigo:"DS-005", nome:"Nicho Ferrara", ambiente:"Cozinha", preco:359, preco_riscado:null,
    medidas:"58 × 86 × 30 cm", descricao:"Nicho industrial suspenso porta-utensílios",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-005.png", oficina:null, detalhe:"assets/DS-005-detalhe.png", perfil:null, medidas:"assets/DS-005-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3ZENOC8230" },
  { codigo:"DS-006", nome:"Kit Cairo", ambiente:"Cozinha", preco:499, preco_riscado:null,
    medidas:"70 × 30 × 25 cm", descricao:"Kit com 2 nichos industriais suspensos",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-006.png", oficina:null, detalhe:"assets/DS-006-detalhe.png", perfil:null, medidas:"assets/DS-006-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/81OOF6UJUV" },
  { codigo:"DS-007", nome:"Suporte Enzo", ambiente:"Cozinha", preco:269, preco_riscado:null,
    medidas:"60 × 44 × 33 cm", descricao:"Suporte industrial suspenso para micro-ondas",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-007.png", oficina:null, detalhe:"assets/DS-007-detalhe.png", perfil:null, medidas:"assets/DS-007-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/T6E2RIJIAZ" },
  { codigo:"DS-008", nome:"Aparador Vitrali", ambiente:"Cozinha", preco:309, preco_riscado:null,
    medidas:"89 × 60 × 19 cm", descricao:"Aparador industrial de cozinha",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-008.png", oficina:null, detalhe:"assets/DS-008-detalhe.png", perfil:null, medidas:"assets/DS-008-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9QCDW97DQN" },
  { codigo:"DS-009", nome:"Prateleira Milano", ambiente:"Cozinha", preco:289, preco_riscado:null,
    medidas:"120 × 41 × 20 cm", descricao:"Prateleira industrial dupla suspensa",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-009.png", oficina:null, detalhe:"assets/DS-009-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3ZTSXBUF01" },
  { codigo:"DS-010", nome:"Carrinho Nômade", ambiente:"Cozinha", preco:379, preco_riscado:null,
    medidas:"55 × 75 × 30 cm", descricao:"Carrinho industrial de cozinha com rodízios",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-010.png", oficina:null, detalhe:"assets/DS-010-detalhe.png", perfil:null, medidas:"assets/DS-010-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/ILM5M1A7LL" },
  { codigo:"DS-011", nome:"Prateleira Jasmin", ambiente:"Cozinha", preco:149, preco_riscado:null,
    medidas:"41 × 32 × 10 cm", descricao:"Prateleira industrial porta-canecas",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-011.png", oficina:null, detalhe:null, perfil:"assets/DS-011-perfil.png", medidas:"assets/DS-011-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/2XRASXSJ8C" },
  { codigo:"DS-012", nome:"Escrivaninha Turim", ambiente:"Escritório", preco:699, preco_riscado:null,
    medidas:"118 × 75 × 53 cm", descricao:"Escrivaninha industrial com gaveta",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-012.png", oficina:null, detalhe:null, perfil:"assets/DS-012-perfil.png", medidas:"assets/DS-012-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/E2V2HVP5W7" },
  { codigo:"DS-013", nome:"Mesa Órion", ambiente:"Escritório", preco:1379, preco_riscado:null,
    medidas:"180 × 118 × 70 cm", descricao:"Mesa gamer industrial com suporte para monitor",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-013.png", oficina:null, detalhe:null, perfil:"assets/DS-013-perfil.png", medidas:"assets/DS-013-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/S3VLVNBEUY" },
  { codigo:"DS-014", nome:"Escrivaninha Toscana", ambiente:"Escritório", preco:469, preco_riscado:null,
    medidas:"67 × 78 × 30 cm", descricao:"Escrivaninha industrial com nichos laterais",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-014.png", oficina:null, detalhe:null, perfil:"assets/DS-014-perfil.png", medidas:"assets/DS-014-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/K4A2NI5S3H" },
  { codigo:"DS-015", nome:"Mesa Atlas", ambiente:"Escritório", preco:1199, preco_riscado:null,
    medidas:"200 × 74 × 90 cm", descricao:"Mesa de reunião industrial corporativa",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-015.png", oficina:null, detalhe:null, perfil:"assets/DS-015-perfil.png", medidas:"assets/DS-015-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FRP8JQSX8M" },
  { codigo:"DS-016", nome:"Nicho Módena", ambiente:"Escritório", preco:419, preco_riscado:null,
    medidas:"70 × 70 × 20 cm", descricao:"Nicho de parede modular com compartimentos assimétricos · Ferro galvanizado · Madeira maciça",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-016.png", oficina:null, detalhe:null, perfil:null, medidas:"assets/DS-016-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FG8BMWXODP" },
  { codigo:"DS-017", nome:"Prateleira Modena", ambiente:"Escritório", preco:459, preco_riscado:null,
    medidas:"120 × 88 × 20 cm", descricao:"Prateleira industrial dupla para livros",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-017.png", oficina:null, detalhe:"assets/DS-017-detalhe.png", perfil:null, medidas:"assets/DS-017-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1XD4G89DMF" },
  { codigo:"DS-018", nome:"Escrivaninha Nórdica", ambiente:"Escritório", preco:279, preco_riscado:null,
    medidas:"80 × 77 × 45 cm", descricao:"Escrivaninha industrial compacta slim",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-018.png", oficina:null, detalhe:"assets/DS-018-detalhe.png", perfil:null, medidas:"assets/DS-018-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/K2I53016FS" },
  { codigo:"DS-019", nome:"Home Office Loft", ambiente:"Escritório", preco:679, preco_riscado:null,
    medidas:"100 × 80 × 55 cm", descricao:"Estação de trabalho suspensa com prateleiras",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-019.png", oficina:null, detalhe:"assets/DS-019-detalhe.png", perfil:null, medidas:"assets/DS-019-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/3QIZN2V8HB" },
  { codigo:"DS-020", nome:"Suporte Kraft", ambiente:"Escritório", preco:259, preco_riscado:null,
    medidas:"50 × 22 × 40 cm", descricao:"Suporte industrial suspenso para impressora",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-020.png", oficina:null, detalhe:"assets/DS-020-detalhe.png", perfil:null, medidas:"assets/DS-020-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/84V7JF8IN7" },
  { codigo:"DS-021", nome:"Mesa Cortez", ambiente:"Escritório", preco:169, preco_riscado:null,
    medidas:"60 × 50 × 30 cm", descricao:"Mesa lateral industrial em C para sofá",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-021.png", oficina:null, detalhe:"assets/DS-021-detalhe.png", perfil:null, medidas:"assets/DS-021-medidas.jpg" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/IR5Q58A0CR" },
  { codigo:"DS-022", nome:"Closet Verona", ambiente:"Quarto", preco:969, preco_riscado:null,
    medidas:"120 × 180 × 40 cm", descricao:"Closet industrial aberto com iluminação LED",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-022.png", oficina:null, detalhe:"assets/DS-022-detalhe.png", perfil:null, medidas:"assets/DS-022-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/NN9QOEMAF1" },
  { codigo:"DS-023", nome:"Criado-Mudo Onyx", ambiente:"Quarto", preco:369, preco_riscado:null,
    medidas:"50 × 45 × 40 cm", descricao:"Criado-mudo industrial com gaveta basculante",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-023.png", oficina:null, detalhe:"assets/DS-023-detalhe.png", perfil:null, medidas:"assets/DS-023-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/OXW6SN8AMI" },
  { codigo:"DS-024", nome:"Banco Aurora", ambiente:"Quarto", preco:279, preco_riscado:null,
    medidas:"60 × 45 × 30 cm", descricao:"Banco sapateira industrial",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-024.png", oficina:null, detalhe:"assets/DS-024-detalhe.png", perfil:null, medidas:"assets/DS-024-medidas.jpg" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9N5OJCNLTT" },
  { codigo:"DS-025", nome:"Sapateira Carbon", ambiente:"Quarto", preco:519, preco_riscado:null,
    medidas:"75 × 90 × 35 cm", descricao:"Sapateira industrial compacta 2 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-025.png", oficina:null, detalhe:"assets/DS-025-detalhe.png", perfil:null, medidas:"assets/DS-025-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KCJO4LLLKM" },
  { codigo:"DS-026", nome:"Prateleira Sienna", ambiente:"Quarto", preco:249, preco_riscado:null,
    medidas:"100 × 37 × 20 cm", descricao:"Prateleira industrial dupla de cabeceira",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-026.png", oficina:null, detalhe:"assets/DS-026-detalhe.png", perfil:null, medidas:"assets/DS-026-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/Q1E8BGLDDS" },
  { codigo:"DS-027", nome:"Criado-Mudo Cedro", ambiente:"Quarto", preco:389, preco_riscado:null,
    medidas:"60 × 60 × 40 cm", descricao:"Criado-mudo industrial com nicho aberto",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-027.png", oficina:null, detalhe:"assets/DS-027-detalhe.png", perfil:null, medidas:"assets/DS-027-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/LO8EJ8KKCV" },
  { codigo:"DS-028", nome:"Sapateira Nero", ambiente:"Quarto", preco:519, preco_riscado:null,
    medidas:"75 × 90 × 35 cm", descricao:"Sapateira industrial escalonada",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-028.png", oficina:null, detalhe:"assets/DS-028-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/ASEMZR3EAP" },
  { codigo:"DS-029", nome:"Criado-Mudo Lumière", ambiente:"Quarto", preco:359, preco_riscado:null,
    medidas:"50 × 40 × 40 cm", descricao:"Criado-mudo industrial com gaveta e tampo de vidro",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-029.png", oficina:null, detalhe:"assets/DS-029-detalhe.png", perfil:null, medidas:"assets/DS-029-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/7Z9H9GCLOP" },
  { codigo:"DS-030", nome:"Arara Amêndoa", ambiente:"Quarto", preco:799, preco_riscado:null,
    medidas:"100 × 180 × 34 cm", descricao:"Arara closet industrial com prateleiras",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-030.png", oficina:null, detalhe:"assets/DS-030-detalhe.png", perfil:null, medidas:"assets/DS-030-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QIZWQUPHRG" },
  { codigo:"DS-031", nome:"Cabideiro Bruma", ambiente:"Quarto", preco:169, preco_riscado:null,
    medidas:"40 × 30 × 26 cm", descricao:"Cabideiro de parede com prateleira · Ferro galvanizado · Madeira maciça",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-031.png", oficina:null, detalhe:"assets/DS-031-detalhe.png", perfil:null, medidas:"assets/DS-031-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/1MSXAFNU4W" },
  { codigo:"DS-032", nome:"Mesa Havana", ambiente:"Quarto", preco:289, preco_riscado:null,
    medidas:"47 × 45 × 45 cm", descricao:"Mesa lateral industrial de cabeceira",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-032.png", oficina:null, detalhe:"assets/DS-032-detalhe.png", perfil:null, medidas:"assets/DS-032-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/AOT16EUG6F" },
  { codigo:"DS-033", nome:"Nicho Terrano", ambiente:"Quarto", preco:299, preco_riscado:null,
    medidas:"50 × 45 × 35 cm", descricao:"Nicho de parede escalonado · Ferro galvanizado · Madeira maciça",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-033.png", oficina:null, detalhe:"assets/DS-033-detalhe.png", perfil:null, medidas:null },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/RTNBETIK05" },
  { codigo:"DS-034", nome:"Prateleira Halo", ambiente:"Quarto", preco:349, preco_riscado:null,
    medidas:"60 × 40 × 30 cm", descricao:"Prateleira industrial tripla com iluminação LED",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-034.png", oficina:null, detalhe:"assets/DS-034-detalhe.png", perfil:null, medidas:"assets/DS-034-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KGE0B6OAX6" },
  { codigo:"DS-035", nome:"Cabideiro Linho", ambiente:"Quarto", preco:299, preco_riscado:null,
    medidas:"50 × 120 × 32 cm", descricao:"Cabideiro industrial suspenso com prateleira",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-035.png", oficina:null, detalhe:null, perfil:"assets/DS-035-perfil.png", medidas:"assets/DS-035-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FZJJD127VH" },
  { codigo:"DS-036", nome:"Nicho Ostra", ambiente:"Banheiro", preco:189, preco_riscado:null,
    medidas:"60 × 50 × 15 cm", descricao:"Nicho industrial suspenso de banheiro 2 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-036.png", oficina:null, detalhe:"assets/DS-036-detalhe.png", perfil:null, medidas:"assets/DS-036-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/FVSG2Z4SEW" },
  { codigo:"DS-037", nome:"Prateleira Costa", ambiente:"Banheiro", preco:169, preco_riscado:null,
    medidas:"60 × 15 × 30 cm", descricao:"Prateleira industrial de banheiro com toalheiro",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-037.png", oficina:null, detalhe:"assets/DS-037-detalhe.png", perfil:null, medidas:"assets/DS-037-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/RZWBNE5J49" },
  { codigo:"DS-038", nome:"Prateleira Salina", ambiente:"Banheiro", preco:179, preco_riscado:null,
    medidas:"60 × 30 × 15 cm", descricao:"Prateleira industrial dupla com barra toalheiro",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-038.png", oficina:null, detalhe:"assets/DS-038-detalhe.png", perfil:null, medidas:"assets/DS-038-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/9XAP2LOVCG" },
  { codigo:"DS-039", nome:"Estante Maresia", ambiente:"Banheiro", preco:409, preco_riscado:null,
    medidas:"60 × 80 × 20 cm", descricao:"Estante industrial de banheiro 4 prateleiras",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-039.png", oficina:null, detalhe:"assets/DS-039-detalhe.png", perfil:null, medidas:"assets/DS-039-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/SA87DUH2PF" },
  { codigo:"DS-040", nome:"Torre Abissal", ambiente:"Banheiro", preco:309, preco_riscado:null,
    medidas:"30 × 120 × 15 cm", descricao:"Torre industrial vertical suspensa de banheiro",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-040.png", oficina:null, detalhe:"assets/DS-040-detalhe.png", perfil:null, medidas:"assets/DS-040-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/GJ2MBH3GEG" },
  { codigo:"DS-041", nome:"Toalheiro Escada", ambiente:"Banheiro", preco:139, preco_riscado:null,
    medidas:"60 × 30 × 15 cm", descricao:"Toalheiro industrial suspenso com prateleira",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-041.png", oficina:null, detalhe:null, perfil:"assets/DS-041-perfil.png", medidas:"assets/DS-041-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QV5Y10946M" },
  { codigo:"DS-042", nome:"Kit Duna", ambiente:"Banheiro", preco:139, preco_riscado:null,
    medidas:"50 × 75 × 15 cm", descricao:"Kit com 2 toalheiros industriais suspensos",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-042.png", oficina:null, detalhe:"assets/DS-042-detalhe.png", perfil:null, medidas:"assets/DS-042-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/GGOS0HXUS2" },
  { codigo:"DS-043", nome:"Toalheiro Mistral", ambiente:"Banheiro", preco:149, preco_riscado:null,
    medidas:"70 × 50 × 15 cm", descricao:"Toalheiro industrial de piso 3 barras",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-043.png", oficina:null, detalhe:null, perfil:"assets/DS-043-perfil.png", medidas:"assets/DS-043-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QWY07YGDY4" },
  { codigo:"DS-044", nome:"Bancada Maresol", ambiente:"Banheiro", preco:379, preco_riscado:null,
    medidas:"59,5 × 46,8 × 37 cm", descricao:"Bancada industrial suspensa de banheiro com toalheiro",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-044.png", oficina:null, detalhe:null, perfil:"assets/DS-044-perfil.png", medidas:"assets/DS-044-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/7XLPYLT9RB" },
  { codigo:"DS-045", nome:"Prateleira Skyline", ambiente:"Sala de Estar", preco:489, preco_riscado:null,
    medidas:"80 × 75,5 × 30,5 cm", descricao:"Prateleira de parede escalonada com 3 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-045.png", oficina:null, detalhe:null, perfil:"assets/DS-045-perfil.png", medidas:"assets/DS-045-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/SJE0S041S5" },
  { codigo:"DS-046", nome:"Aparador Esguio", ambiente:"Sala de Estar", preco:189, preco_riscado:null,
    medidas:"40 × 70 × 20 cm", descricao:"Aparador console estreito de 2 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-046.png", oficina:null, detalhe:"assets/DS-046-detalhe.png", perfil:null, medidas:"assets/DS-046-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/D8TLJHMFP0" },
  { codigo:"DS-047", nome:"Rack Horizonte", ambiente:"Sala de Estar", preco:369, preco_riscado:null,
    medidas:"80 × 25,5 × 40 cm", descricao:"Rack de TV baixo industrial de 2 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-047.png", oficina:null, detalhe:"assets/DS-047-detalhe.png", perfil:null, medidas:"assets/DS-047-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/79Z4INI76M" },
  { codigo:"DS-048", nome:"Floreira Zigue", ambiente:"Sala de Estar", preco:369, preco_riscado:null,
    medidas:"50 × 180 × 24 cm", descricao:"Suporte de plantas escalonado em Z de 3 níveis",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-048.png", oficina:null, detalhe:"assets/DS-048-detalhe.png", perfil:null, medidas:"assets/DS-048-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/EAAN8RC2EI" },
  { codigo:"DS-049", nome:"Mesa Abraço", ambiente:"Sala de Estar", preco:909, preco_riscado:null,
    medidas:"170 × 70 × 40 cm", descricao:"Mesa lateral em C para sofá",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-049.png", oficina:null, detalhe:"assets/DS-049-detalhe.png", perfil:null, medidas:"assets/DS-049-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/QV5BM83FF3" },
  { codigo:"DS-050", nome:"Mesa Litoral", ambiente:"Sala de Estar", preco:459, preco_riscado:null,
    medidas:"70 × 34 × 60 cm", descricao:"Mesa de centro com tampo claro e base em U",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-050.png", oficina:null, detalhe:"assets/DS-050-detalhe.png", perfil:null, medidas:"assets/DS-050-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/KTQ43U58CD" },
  { codigo:"DS-051", nome:"Painel Cinema", ambiente:"Sala de Estar", preco:1499, preco_riscado:null,
    medidas:"200 × 185 × 34 cm", descricao:"Painel rack de TV com estante lateral",
    material:"Ferro galvanizado · Madeira maciça", acabamento:"Pintura fosca · Junções sem emenda",
    imagens:{ ambiente:"assets/DS-051.png", oficina:null, detalhe:"assets/DS-051-detalhe.png", perfil:null, medidas:"assets/DS-051-medidas.png" },
    link_checkout:"https://dilino-studio.pay.yampi.com.br/r/28H4HJMHSV" },
];

/* Vitrine "Mais Procuradas" da home: ordem + preço/selo promocional.
   preco aqui sobrepõe o do catálogo SÓ na home. badge aceita "-20%" ou "Novo". */
window.DILINO_DESTAQUES = [
  { codigo:"DS-008", preco:1189, badge:"-20%" },
  { codigo:"DS-002", preco:949, badge:"-20%" },
  { codigo:"DS-012", preco:999, badge:"Novo" },
  { codigo:"DS-023", preco:449, badge:"-20%" },
  { codigo:"DS-032", preco:749, badge:null },
  { codigo:"DS-001", preco:169, badge:null },
  { codigo:"DS-016", preco:419, badge:"Novo" },
  { codigo:"DS-030", preco:329, badge:null },
];
